pipeline {
    agent any

    stages {
        stage("Install") {
            steps {
                dir('app') {
                    sh 'npm ci'
                }
            }
        }
        // LANCER LES TESTS ET LE LINT
        stage("Test") {
            steps {
                dir('app') {
                    sh 'npm test'
                }
            }
        }

        stage("Lint") {
            steps {
                dir('app') {
                    sh 'npm run lint'
                }
            }
        }
    }   
}