pipeline {
    agent any

    stages {
        stage("Install") {
            steps {
                dir('app') {
                    sh 'npm ci'
                }
            }
        }
        // LANCER LES TESTS ET LE LINT
        stage("Quality") {
            parallel {
                stage("Lint") {
                    steps {
                        dir('app') {
                            sh 'npm run lint'
                        }
                    }
                }

                stage("Test") {
                    steps {
                        dir('app') {
                            sh 'npm test'
                        }
                    }
                }
            }
        }
    }   
}